spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5434}/${DATABASE_NAME:twitter}
spring.datasource.username=${DATABASE_USERNAME:twitter}
spring.datasource.password=${DATABASE_PASSWORD:twitter}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

fanout.celebrity-threshold=10000

server.port=8081